global:
  replicaCount: 1
  namespace: flowsource
  #configMapName: gcip-iap-authui-configmap

authui:
  service:
    type: ClusterIP
    annotations: |
      cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'