apiVersion: v1
kind: Service
metadata:
  name: authui-service-np
  namespace: flowsource
  annotations:
      cloud.google.com/neg: '{"exposed_ports": {"32098":{"name": "flowsource-authui-neg"}}}'
spec:
  type: ClusterIP  
  ports:
  - name: http
    port: 32098
    targetPort: http
    protocol: TCP
  selector:
    app: authui