apiVersion: v1
kind: Service
metadata:
  name: authui-service-np
  namespace: {{ .Values.global.namespace }}
  {{- if .Values.global.authui.service.annotations }}
  annotations:
    {{- .Values.global.authui.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.global.authui.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: authui