apiVersion: v1
kind: Service
metadata:
  name: authui-service-np
  namespace: flowsource
  annotations:
      cloud.google.com/neg: '{"exposed_ports": {"32098":{"name": "flowsource-auth-neg"}}}'
spec:
  type: ClusterIP
  ports:
  - port: 32098
    protocol: TCP
  selector:
    app: authui