apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: authui-secrets-provider
  namespace: flowsource
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.global.authui.secret.gcpProjectId }}/secrets/AUTHUI_FIREBASE_API_KEY/versions/latest"
        path: AUTHUI_FIREBASE_API_KEY
      - resourceName: "projects/{{ .Values.global.authui.secret.gcpProjectId }}/secrets/AZURE_TENANT_ID/versions/latest"
        path: AZURE_TENANT_ID        
  secretObjects:
    - secretName: gcip-iap-authui-secret
      data:
      - key: API_KEY
        objectName: AUTHUI_FIREBASE_API_KEY
      - key: TENANT_ID
        objectName: AZURE_TENANT_ID        
      type: Opaque