{{- if eq .Values.authui.authuiSecrets.useSecretProvider false }}
apiVersion: v1
kind: Secret
metadata:
  name: authui-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.authui.authuiSecrets.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }} 
{{ end }} 