apiVersion: v1
kind: Service
metadata:
  name: authui-service-np
  namespace: flowsource
spec:
  type: ClusterIP
  annotations: |
      cloud.google.com/neg: '{"exposed_ports": {"32098":{"name": "flowsource-authui-neg"}}}'
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: authui