apiVersion: v1
kind: Service
metadata:
  name: authui-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: authui
  annotations:
    #networking.gke.io/load-balancer-type: "Internal"
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  ports:
  - port: 80  # External port
    targetPort: 8080  # Internal container port
    protocol: TCP
  selector:
    app: authui