apiVersion: v1
kind: Service
metadata:
  name: authui-service-np
  namespace: flowsource
  annotations:
      {{ .Values.global.authui.service.annotations }}
spec:
  type: {{ .Values.global.authui.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: authui