apiVersion: apps/v1
kind: Deployment
metadata:
  name: authui-deployment
  namespace: flowsource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authui
  template:
    metadata:
      labels:
        app: authui
    spec:
      containers:
      - image: gcr.io/gcip-iap/authui
        imagePullPolicy: Always
        name: authui
        env:
        - name: DEBUG_CONSOLE
          value: "true"
        - name: UI_CONFIG
          value: |
            {
              "$(API_KEY)": {
                "authDomain": "cog01hy0xaqm3kfh4mr4t3em9ex2m.firebaseapp.com",
                "displayMode": "optionFirst",
                "selectTenantUiTitle": "Flowsource Auth UI",
                "selectTenantUiLogo": "",
                "styleUrl": "",
                "tenants": {
                  "_": {
                    "displayName": "Flowsource Auth UI",
                    "iconUrl": "https://www.gstatic.com/firebasejs/ui/2.0.0/imagesauth/anonymous.png",
                    "logoUrl": "",
                    "buttonColor": "#007bff",
                    "immediateFederatedRedirect": true,
                    "signInFlow": "redirect",
                    "signInOptions": [
                      {
                        "provider": "microsoft.com",
                        "customParameters": {
                          "tenant": "$(TENANT_ID)"
                        }
                      }
                    ]
                  }
                }
              }
            }          
        envFrom:
          - secretRef:
              name: gcip-iap-authui-secret
        volumeMounts:
          - name: authui-secrets-volume
            mountPath: /mnt/authui-secrets-store
            readOnly: true
        ports:
        - containerPort: 8080
      volumes:
          - name: authui-secrets-volume
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: authui-secrets-provider
                name: authui-secrets