apiVersion: v1
kind: Service
metadata:
  name: authui-service-np
  namespace: flowsource
  annotations:
      cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: authui