apiVersion: v1
kind: Service
metadata:
  name: authui-service
  annotations: 
    networking.gke.io/load-balancer-type: "Internal"
  namespace: flowsource
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: authui
  type: LoadBalancer