apiVersion: v1
kind: Secret
metadata:
  name: authui-secrets
  namespace: flowsource
type: Opaque
stringData: 
  UI_CONFIG: |
    {
      "AIzaSyC_4cpHQJSwdfj4UbA3LYlFrQvYoSXjCwI": {
        "authDomain": "cog01hy0xaqm3kfh4mr4t3em9ex2m.firebaseapp.com",
        "displayMode": "optionFirst",
        "selectTenantUiTitle": "Flowsource Auth UI",
        "selectTenantUiLogo": "",
        "styleUrl": "",
        "tenants": {
          "_": {
            "displayName": "Flowsource Auth UI",
            "iconUrl": "https://www.gstatic.com/firebasejs/ui/2.0.0/imagesauth/anonymous.png",
            "logoUrl": "",
            "buttonColor": "#007bff",
            "immediateFederatedRedirect": true,
            "signInFlow": "redirect",
            "signInOptions": [
              {
                "provider": "microsoft.com",
                "customParameters": {
                  "tenant": "de08c407-19b9-427d-9fe8-edf254300ca7"
                }
              }
            ]
          }
        }
      }
    }