apiVersion: v1
kind: Service
metadata:
  name: authui-service-np
  namespace: flowsource
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32098
  selector:
    app: authui