apiVersion: v1
kind: ConfigMap
metadata:
  name: gcip-iap-authui-configmap
  namespace: {{ .Values.global.namespace }}
  labels: 
    app: authui 
data:
  {{- range $key, $val := .Values.authui.authuiConfig }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}