allconfigurations:
  files:
    - name: all-configurations.yaml
      content: |-
        apiVersion: backstage.io/v1alpha1
        kind: Location
        metadata:
          name: all-configurations
          description: A collection of all Backstage entities
        spec:
          targets:
            - ./org.yaml
            - ./systems.yaml
            # - ./remote-templates.yaml
    - name: remote-tenmplates.yaml
      content: |-
        ---
        # apiVersion: backstage.io/v1alpha1
        # kind: Location
        # metadata:
        #   name: templates-remote
        #   description: A collection of remotely available templates
        # spec:
        #   type: url
        #   targets:
    - name: systems.yaml
      content: |-
        apiVersion: backstage.io/v1alpha1
        kind: System
        metadata:
          name: examples
        spec:
          owner: guests
    - name: org.yaml
      content: |-
        ---
        # https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
        apiVersion: backstage.io/v1alpha1
        kind: Group
        metadata:
          name: guests
        spec:
          type: team
          children: []

        ---
        apiVersion: backstage.io/v1alpha1
        kind: Group
        metadata:
          name: sample-team
          description: Group for Sample Team
        spec:
          type: team
          profile:
            # Intentional no displayName for testing
            email: sample-temp-mail-id@example.com
            # picture: https://avatars.dicebear.com/api/identicon/skygrade-team@example.com.svg?background=%23fff&margin=25
          parent: backstage
          children: []

        ---
        # This user is added as an example, to make it more easy for the "Guest"
        # sign-in option to demonstrate some entities being owned. In a regular org,
        # a guest user would probably not be registered like this.
        apiVersion: backstage.io/v1alpha1
        kind: User
        metadata:
          name: guest
        spec:
          profile:
            displayName: Guest User
            email: guest@example.com
            # picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
          memberOf: [sample-team, guests]

        ---
        apiVersion: backstage.io/v1alpha1
        kind: User
        metadata:
          name: John
        spec:
          profile:
            # Intentional no displayName for testing
            email: john@example.com
            # picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
          memberOf: [sample-team]
    - name: alloydb-ca.crt
      content: |-
        -----BEGIN CERTIFICATE-----
        MIIFAzCCAuugAwIBAgIUEXJS6C+3AIoUh81+VuSvxo/TFBUwDQYJKoZIhvcNAQEL
        BQAwETEPMA0GA1UEAwwGdW51c2VkMB4XDTI1MDEyNjA3MTYxMVoXDTM1MDEyNDA3
        MTYxMVowETEPMA0GA1UEAwwGdW51c2VkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
        MIICCgKCAgEAs0zEx+RFCEeCsCBTiMhAhmRuGvxkd4SbMKmYszPKetghWxhItY3t
        bAPp1VOC9jhEHWOXftTBom9pjAfmvlKL3YW1cwJO15MrVOT+dlvtnTLqSKh6fR2j
        TiVgpg1bpdmdj2I2NYSloL1JLw0VSHTCGFbgi6ItMadCJGOjYh/VS5wrpybnIVVe
        pf8ER9ZgVS6OiVOyWTt2odt2FLiv4wfjRmyhG5O6NbXQC+nPFt6nuv3FYIaRjorj
        HDSitUEWYY6uZrF7xEtXjhA1HlTYG5HLtLGU2z6WU/awfXgutrAKjMQ9Q3UtvgPB
        qjwhsWtTUuz1ERh4TdiuhxaQt2H6EG7x9X1dfvgalKE/v17n1paKmGdoqlINEQTA
        5kJdm1IGAQzUWLKIaeMJzvS0v89j4+OYd2Hk2lqCBBb6zIX7UUkQ1jNmSAlRG2Ba
        SDp5q5X1KcIlOFw2bF6AaQClCtiv1VToZrRm/fuRNWdxm5ikoEdw7vEa4DgnNfe8
        xmGAyWbMB7PHyAzIWyw/z2tJJXpGiByxqhp8KmJsjwsr4pxeHyrUcysJvKmGCGDw
        cWsBdcDEjUU5tU0rLir3f9fPTOKsL56QFifeg1fQzpqkpo0yH6aS/qzu5J2Ah5EU
        vn3zvtYAfuPNF5Rwyu4VpQ8xoiwkiJOARPb605aux8fmB15N+rJi1ucCAwEAAaNT
        MFEwHQYDVR0OBBYEFNVI8TSFr/PhZhJ+Dpd9EZWFFMffMB8GA1UdIwQYMBaAFNVI
        8TSFr/PhZhJ+Dpd9EZWFFMffMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
        BQADggIBACmzwykzrpCMOc9IEuwV03PtBKA187ic6KLhO0XAdr7D8QUK/MxAfQBQ
        4FTVUc9Xdbxt7wj1axWy70ftfPGltmirGXi9ZtcslF/UjlMpzradshZdTDCFVlEP
        dL9UYm8eJClDeW6P5XdcN+93+qv6AaWUdSsJQSj1JyyeUDBjj++WtNa9AcVBObCE
        kCC4/lHB+UPrtQ4tS4DzfMfhfAY2iusLleZBZG4dqTSPuJ0qakoHGl8xNJdmlhmN
        jFgPzLvyyv2K+X0FZuqmIlfybFUWT/4606sr0Cc38L0hgJM0GrPmobKO8Kq6HoDy
        WkSFVFQp0LixXiJICrJyCIk5CqTaFD+6vqKZlNFAovd/5pMb5cjgRKE0ydWcf1Wd
        dy/eyNHDSOnS0v40bm7XLl5qPCiUnw7Ebw/1RWdTS8uMPJVokXEDk5V995ERQiNj
        diDoTSw7hioMQ0kc6X2MgSke1gSU7jbeWPNrGWA26gTvEe4QeYtIkobjUbbvSoyO
        LBN8ER4Bgr6ZoeNDJvLn/f2mYNg0USpmdRjBS9ykmTkeZnAMaEnk2QBCGkqjtkUt
        iLQ5u0g5YttZ6lJETWxVxiEDqUymEkSTz4HO4tkqMarTl5Z4gsZ088sMjDCXAEUE
        Xwh8pw3fIGNMoTRtYBQbF6RErnHQEC2G7Q9LJJh8x+w7Zgv+P3LW
        -----END CERTIFICATE-----