{{- if eq .Values.flowsource.flowsourceSecrets.useSecretProvider false }}
apiVersion: v1
kind: Secret
metadata:
  name: flowsource-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.flowsource.flowsourceSecrets.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }} 
{{ end }}