apiVersion: v1
kind: ConfigMap
metadata:
  name: flowsource-cm
  namespace: {{ .Values.global.namespace }}
data:
  {{- range $key, $val := .Values.flowsource.flowsourceConfig }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
