# kubernetes/flowsource-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flowsource
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.flowsource.service.type }}
  selector:
    app: flowsource
  ports:
    - name: http
      port: 7007
      targetPort: http
      protocol: TCP